### ISSUE TITLE
Left/Right click on a point

### ISSUE THREAD

**Issue by Volodymyr-13** [gpxstudio/gpx.studio#33]
This menu shown after left click, which is bad UX/UI. Please fix.

![Screenshot](https://github.com/user-attachments/assets/96d9d0c3-73a3-4085-a96c-8c325736b7f1)

 - **left click** could: select/deselect point or so
 - **right click** should bring a menu, if it's available, in this case it is

**Comment by nevvkid** [comment]
@Volodymyr-13 I am not really sure if I understand correctly what your issue is. What I can see trying the feature is that every time I click "Start loop here" while doing this on a already existing point - there is a new point on the track created. Resulting in something like this if you do it multiple times: 
<img width="885" alt="image" src="https://github.com/user-attachments/assets/c0936707-d57d-48bf-aa8c-7fe887032b72">

**Comment by Volodymyr-13** [comment]
@nevvkid when I left-click on any point, a menu appears. This menu should not be shown because menus should only be displayed when I right-click.

**Comment by Volodymyr-13** [comment]
@vcoppe this is not woking at all. Left click should do nothing, right click should bring menu. 
Left click also should hide menu, which opened from right click. Currently it's a total mess...
